# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f52a4c211818295c6a30ec1cae482744c8a8b4dae88b4486aea151e1b624b4ba452b272612eaf7d960c617aae2482b9668ae7fc3482177c0ee5f7eb456ab6619

test:
  secret_key_base: a2ac352878d13d02a6963deda955d75d9c31255c5149f99afba34d450f9b3d4bb1ef2d3a3a2bcbb205a2b4af89f9424ba4eb259e8367f585d05628453ce256c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
